### ISSUE TITLE
Patch Tracking

### ISSUE THREAD

**Issue by zephyrbot** [zephyrproject-rtos/infrastructure-old#98]
**_Reported by Robert Beatty:_**
As a developer I would like to have CI facilitate updates in tracking.
{panel}
Goals
* lower overhead for developers (less button clicks, time spent updating tickets)
* Increase tracking
* Automate status updates and tracking
* CI will not inhibit doing the right thing
{panel}
+Acceptance Criteria+
* All patches are tracked with corrosponding JIRA tickets

- [x] GH-102: Submission Git Hooks
- [x] GH-101: Improvement Issuetype
- [x] GH-100: Automatic Tracking
- [x] GH-99: Automatic Merge Updates

(Imported from Jira INF-99)

**Comment by zephyrbot** [comment]
**_by Robert Beatty:_**

_Anas Nashif_  and _Mark Linkmeyer_ ,


Please take a look at this EPIC for CI.  Goal is to get CI to work for the developer and encourage good behavior.
